spring:
  application:
    name: qiniuyun
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
qiniu:
  kodo:
    # 配置accessKey
    accessKey: 
    # 配置secretKey
    secretKey: 
    bucket: 
    # 配置域名
    prefix: 



